class Error(Exception):
    pass


class NotFoundError(Error):
    pass
